"5tera": "XAATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
"tera3": "GTGTCAGTCACTTCCA"
"5tera-short": "XAGGGAGGACGATGCGG"
"5tera3":
    "5adapter": "XAATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
    "3adapter": "GTGTCAGTCACTTCCA"
