samples: "config/samples.csv"

dirs: "config/dirs.yaml"

sqldb: "no" # ["yes"|"no"]

singularity_container: "teraseq_snakemake.sif"

resources: "config/resources.yaml"

ref_links: "config/ref_links.yaml"

adapters: "config/adapters.yaml"
