samples: /home/jan/playground/TERA-Seq_snakemake/config/samples.csv

adapters: /home/jan/playground/TERA-Seq_snakemake/config/adapters.yaml

ref_links: /home/jan/playground/TERA-Seq_snakemake/config/ref_links.yaml

dirs: /home/jan/playground/TERA-Seq_snakemake/config/dirs.yaml
