"hg38":
    "cip.decap":
        "hsa.dRNASeq.HeLa.polyA.CIP.decap.REL5.long.1"
    "other.libs":
        "hsa.dRNASeq.HeLa.polyA.decap.REL5.long.1"
        "hsa.dRNASeq.HeLa.polyA.REL5.long.1"
        "hsa.dRNASeq.HeLa.polyA.REL5OH.long.1"
"mm10":
"sc3":
